#!/bin/bash

# Установка утилит мониторинга
yum install -y {jnet,h,io,if,a}top iptraf nmon

# Скачиваем, можно через wget
curl -LO https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz

# Распаковка архивов 
tar xzvf node_exporter-*.t*gz

# Добавляем пользователей
useradd --no-create-home --shell /bin/false node_exporter

# Установка node_exporter

# Копируем файлы в /usr/local
cp node_exporter-*.linux-amd64/node_exporter /usr/local/bin
chown node_exporter: /usr/local/bin/node_exporter

# Создаём службу node exporter

cd /home/

git clone git@github.com:AleksandrMalinovskiy/monitoring.git

mv /home/monitoring/node_exporter.service /etc/systemd/system/

systemctl daemon-reload
systemctl start node_exporter
systemctl status node_exporter
systemctl enable node_exporter

echo "node_exporter установлен" 


