#!/bin/bash
cd /home/
git clone git@github.com:AleksandrMalinovskiy/monitoring.git

curl -LO https://github.com/prometheus/prometheus/releases/download/v2.34.0/prometheus-2.34.0.linux-amd64.tar.gz

# Распаковка архивов 
tar xzvf prometheus-*.t*gz

# Добавляем пользователей
useradd --no-create-home --shell /usr/sbin/nologin prometheus

mkdir {/etc/,/var/lib/}prometheus
cp -vi prometheus-*.linux-amd64/prom{etheus,tool} /usr/local/bin
cp -rvi prometheus-*.linux-amd64/{console{_libraries,s},prometheus.yml} /etc/prometheus/
chown -Rv prometheus: /usr/local/bin/prom{etheus,tool} /etc/prometheus/ /var/lib/prometheus/

# Настраиваем сервис

mv /home/monitoring/prometheus.service /etc/systemd/system/

# Конфиг prometheus
rm -f /etc/prometheus/prometheus.yml
mv /home/monitoring/prometheus.yml /etc/prometheus/

# Запускаем сервис Prometheus
systemctl daemon-reload
systemctl start prometheus
systemctl status prometheus
systemctl enable prometheus

echo "prometheus установлен"

# Установка Grafana

mv /home/monitoring/grafana.repo /etc/yum.repos.d/

# Установка
yum install grafana

# Запуск
systemctl daemon-reload
systemctl start grafana-server
systemctl status grafana-server

echo "grafana установлена"



